# -*- coding: utf-8 -*-
# Structured content for Nicholas B. King's academic site, transcribed from his CV (2026).

JOURNAL_ARTICLES = [
    ("2025", 'DeBono N, Amar V*, Hardy H*, Schubauer-Berigan M, Ruths D, <strong>King NB</strong>. "A large language model-based tool for identifying relationships to industry in research on the carcinogenicity of benzene, cobalt, and aspartame." <em>Environmental Health</em> 24.'),
    ("2025", 'DeBono N, Amar V*, Hardy H*, Schubauer-Berigan M, Ruths D, <strong>King NB</strong>. "The use of a large language model to identify industry-funded research in carcinogenic hazard evaluations." <em>Occupational &amp; Environmental Medicine</em> 82.'),
    ("2023", 'Trudeau C*, <strong>King NB</strong>, Guastavino C. "Investigating sonic injustice: a review of published research." <em>Social Science &amp; Medicine</em> 326.'),
    ("2023", 'Oei H*, Ruths D, <strong>King NB</strong>. "Who Controlled the Evidence? Question Answering for Disclosure Information Retrieval." <em>Proceedings of Machine Learning Research</em> 209.'),
    ("2022", 'Okhmatovskaia A*, Buckeridge DL, Shen Y*, Ganser I*, <strong>King NB</strong>, Collier N, Meng Z. "A conceptual framework for representing events under public health surveillance." <em>Studies in Health Technology and Informatics</em> 294.'),
    ("2022", 'Meng Z, Okhmatovskaia A*, Polleri M*, Powell G, Shen Y, Fu Z, Ganser I*, <strong>King NB</strong>, Buckeridge D, Collier N. "BioCaster in 2021: Detecting Disease Outbreaks from Global News Media." <em>Bioinformatics</em> 38(18).'),
    ("2021", 'Dimitris M*, Gittings M*, <strong>King NB</strong>. "How Global is Global Health Research? A Large-Scale Analysis of Trends in Authorship." <em>BMJ Global Health</em> 6(1).'),
    ("2021", 'Harper SB, Riddell C*, <strong>King NB</strong>. "Declining Life Expectancy in the United States: Missing the Trees for the Forest." <em>Annual Review of Public Health</em> 42(1).'),
    ("2020", '<strong>King NB</strong>. "Harm Reduction: A Misnomer." <em>Health Care Analysis</em> 28.'),
    ("2020", 'Cooper JE*, Benmarhnia T*, Koski A, <strong>King NB</strong>. "Cash transfer programs have differential effects on health: A review of the literature from low and middle-income countries." <em>Social Science &amp; Medicine</em> 247.'),
    ("2020", '<strong>King NB</strong>, Koski A. "Defining global health as public health somewhere else." <em>BMJ Global Health</em> 5:e002172.'),
    ("2018", 'Drouin O*, Young M, <strong>King NB</strong>. "Message framing and counseling of parents on children’s physical activity – An experimental study." <em>Health Psychology and Behavioral Medicine</em> 6(1).'),
    ("2018", 'Carabali M*, Austin N*, <strong>King NB</strong>, Kaufman J. "The zika epidemic and abortion in Latin America: a scoping review." <em>Global Health Research and Policy</em> 3(15).'),
    ("2018", '<strong>King NB</strong>, Harper SB, Young M, Berry SC, Voigt K*. "The Impact of Social and Psychological Consequences of Disease on Judgments of Disease Severity: An Experimental Study." <em>PLOS ONE</em> 13(4).'),
    ("2017", 'Huang J*, <strong>King NB</strong>. "Epigenetics Changes Nothing: What a New Scientific Field Does and Does Not Mean for Social Justice." <em>Public Health Ethics</em> 11(1).'),
    ("2017", 'Voigt K*, <strong>King NB</strong>. "Out of alignment? Limitations of the Global Burden of Disease in assessing the allocation of global health aid." <em>Public Health Ethics</em> 10(3).'),
    ("2017", 'Benmarhnia T*, Alexander S, Price K, Smargiassi S, <strong>King NB</strong>, Kaufman J. "The heterogeneity of vulnerability in public health: a heat wave action plan as a case study." <em>Critical Public Health</em> 28.'),
    ("2016", '<strong>King NB</strong>, Harper SB, Strumpf E. "Has the Increase in Disability Insurance Participation Contributed to Increased Opioid-Related Mortality?" <em>Annals of Internal Medicine</em> 165(10): 729–730.'),
    ("2016", 'Benmarhnia T*, Auger N, Kaiser D, Bailey Z*, <strong>King NB</strong>, Kaufman J. "A difference-in-differences approach to assess the effect of a heat action plan on heat-related mortality and equity in Montreal, Quebec." <em>Environmental Health Perspectives</em> 24(11). <span class="note">Honorable Mention, Best Environmental Epidemiology Papers of 2016, International Society for Environmental Epidemiology.</span>'),
    ("2016", 'Campbell J*, <strong>King NB</strong>. "‘Unsettling Circularity’: Clinical Trial Enrichment and the Evidentiary Politics of Chronic Pain." <em>Biosocieties</em> 12(2).'),
    ("2015", 'Richardson R*, Charters T*, <strong>King NB</strong>, Harper SB. "Trends in educational inequalities in drug poisoning mortality in the United States, 1994-2010." <em>American Journal of Public Health</em> 105(9).'),
    ("2014", '<strong>King NB</strong>, Fraser V*, Boikos C*, Richardson R*, Harper SB. "Determinants of Increased Opioid-Related Mortality in the United States and Canada, 1990-2013: A Systematic Review." <em>American Journal of Public Health</em> 104(8).'),
    ("2014", 'Harper SB, <strong>King NB</strong>, et al. "Juicios de valor implícitos en la medición de las desigualdades en salud." <em>Revista Panamericana de Salud Pública</em> 35(4).'),
    ("2014", 'Voigt K*, <strong>King NB</strong>. "Disability Weights in the Global Burden of Disease 2010: Two Steps Forward, One Step Back?" <em>Bulletin of the World Health Organization</em> 92.'),
    ("2014", '<strong>King NB</strong>. "Contagion: A Misnomer for Financial Crisis." <em>Journal of Public Health</em> 36(1).'),
    ("2013", 'Harper SB, <strong>King NB</strong>, Young M. "Impact of Selective Evidence Presentation of Health Inequality Trends: An Experimental Study." <em>PLOS ONE</em> 8(5).'),
    ("2013", '<strong>King NB</strong>, Fraser V*. "Untreated Pain, Narcotics Regulation, and Global Health Ideologies." <em>PLOS Medicine</em> 10(4). <span class="note">PLOS Medicine Weekly Editor’s Pick.</span>'),
    ("2013", 'Young ME, <strong>King NB</strong>, Harper SB, Humphreys KR. "The influence of popular media on perceptions of personal and population risk in possible disease outbreaks." <em>Health, Risk, and Society</em> 15(1).'),
    ("2013", '<strong>King NB</strong>, Harper SB, Young ME. "Who Cares About Health Inequalities? Cross-country Evidence from the World Health Survey." <em>Health Policy and Planning</em> 28(5): 558–571.'),
    ("2012", '<strong>King NB</strong>, Harper SB, Young M. "Use of relative and absolute effect measures in reporting health inequalities: structured review." <em>BMJ</em> 345.'),
    ("2012", 'Huttenhower C, Gevers D, et al. (+multiple authors including <strong>King NB</strong>). "Structure, Function and Diversity of the Human Microbiome in an Adult Reference Population." <em>Nature</em> 486 (14 June).'),
    ("2012", 'Methé BA, Nelson KE, et al. (+multiple authors including <strong>King NB</strong>). "A Framework for Human Microbiome Research." <em>Nature</em> 486 (14 June).'),
    ("2012", '<strong>King NB</strong>. "Invited Commentary: Biodefense and the Production of Knowledge: Rethinking the Problem." <em>Journal of Medical Ethics</em> 39.'),
    ("2012", '<strong>King NB</strong>. "Case Discussion: Health Inequities in First Nations Communities and Canada’s Response to the H1N1 Influenza Pandemic." In <em>Population and Public Health Ethics: Cases from Research, Policy, and Practice</em>. Canadian Institutes of Health Research – Institute of Population and Public Health / University of Toronto Joint Centre for Bioethics.'),
    ("2010", 'Harper SB, <strong>King NB</strong>, et al. "Implicit Value Judgments in the Measurement of Health Inequalities." <em>Milbank Memorial Fund Quarterly</em> 88(1). <span class="note">Harper and King share equal status as primary co-authors.</span>'),
    ("2008", 'Ornt DB, Aron DC, <strong>King NB</strong>, et al. "Population Medicine in a Curricular Revision at Case Western Reserve." <em>Academic Medicine</em> 83(4).'),
    ("2006", 'Aiello S, <strong>King NB</strong>, Foxman B. "Antimicrobials and the Ethics of Drug Development." <em>American Journal of Public Health</em> 96(11).'),
    ("2006", 'Berg JW, <strong>King NB</strong>. "Strange Bedfellows? Reflections on Bioethics’ Role in Disaster Response Planning." <em>American Journal of Bioethics</em> 6.'),
    ("2005", '<strong>King NB</strong>. "The Ethics of Biodefense." <em>Bioethics</em> 19(4).'),
    ("2004", '<strong>King NB</strong>. "The Scale Politics of Emerging Diseases." <em>Osiris</em> 19.'),
    ("2003", '<strong>King NB</strong>. "The Influence of Anxiety: September 11th, Bioterrorism, and American Public Health." <em>Journal of the History of Medicine and the Allied Sciences</em> 58(4).'),
    ("2002", '<strong>King NB</strong>. "Security, Disease, Commerce: Ideologies of Post-Colonial Global Health." <em>Social Studies of Science</em> 32(5/6).'),
    ("2002", '<strong>King NB</strong>. "Dangerous Fragments." <em>Grey Room</em> 7 (Spring).'),
]

BOOK_CHAPTERS = [
    ("2023", 'Benyekhlef K, Amicelle A, <strong>King NB</strong>, Tanner S. "Technologies de l’information." In Frédéric Mérand and Jennifer Welsh, <em>Le Monde D’Après: Les conséquences de la COVID-19 sur les relations internationales</em>. Université de Montréal Press.'),
    ("2021", '<strong>King NB</strong>. "Science and Public Policy in a Post-Pandemic World." In Jean-Louis Denis, Catherine Régis &amp; Daniel Weinstock, Eds., <em>Pandemic Societies</em>. Montreal: McGill-Queen’s University Press.'),
    ("2020", 'Piper A, Kraicer E, <strong>King NB</strong>, et al. "Evidence." In Andrew Piper, <em>Can We Be Wrong? The Problem of Textual Evidence in a Time of Data</em>. New York: Cambridge University Press.'),
    ("2020", '<strong>King NB</strong>. "Technological Fixes and Antimicrobial Resistance." In Zeb Jamrozik &amp; Michael Selgelid, Eds., <em>Ethics and Antimicrobial Resistance: Collective Responsibility for Global Public Health</em>.'),
    ("2017", '<strong>King NB</strong>. "Equality and Inequality in American Health Care (Revised)." In Eileen E. Morrison, Ed., <em>Health Care Ethics: Critical Issues for the 21st Century</em>. Sudbury, MA: Jones &amp; Bartlett.'),
    ("2016", '<strong>King NB</strong>. "Justice, Evidence, and Interdisciplinary Health Inequalities Research." In Mara Buchbinder, Ed., <em>Understanding Health Inequalities and Justice: Bridging Perspectives for New Conversations</em>. University of North Carolina Press.'),
    ("2015", '<strong>King NB</strong>. "Mediating Panic: The Iconography of New Infectious Threats, 1936-2009." In Robert Peckham, Ed., <em>Empires of Panic: Epidemics and Colonial Anxieties</em>. Hong Kong: Hong Kong University Press.'),
    ("2012", '<strong>King NB</strong>. "Equality and Inequality in American Health Care (Revised)." In Eileen E. Morrison, Ed., <em>Health Care Ethics: Critical Issues for the 21st Century</em>. Sudbury, MA: Jones &amp; Bartlett.'),
    ("2011", '<strong>King NB</strong>. Introduction to reprint of "The Influence of Anxiety: September 11, Bioterrorism, and American Public Health." In John Charles Goshert, Ed., <em>Entering the Academic Conversation</em>. Glenview, IL: Pearson.'),
    ("2009", '<strong>King NB</strong>. "Equality and Inequality in American Health Care." In Eileen E. Morrison, Ed., <em>Health Care Ethics: Critical Issues for the 21st Century</em>. Sudbury, MA: Jones &amp; Bartlett.'),
    ("2008", '<strong>King NB</strong>. "Networks, Disease, and the Utopian Impulse." In S. Harris Ali &amp; Roger Keil, Eds., <em>Networked Disease: Emerging Infections in the Global City</em>. Malden, MA: Wiley-Blackwell.'),
    ("2006", '<strong>King NB</strong>. "The Ethics of Biodefense." In Michael J. Selgelid, et al., Eds., <em>Ethics and Infectious Disease</em>. Malden, MA: Blackwell.'),
    ("2003", '<strong>King NB</strong>. "Immigration, Race, and Geographies of Difference in the Tuberculosis Pandemic." In Matthew Gandy &amp; Alimuddin Zumla, Eds., <em>Return of the White Plague: Global Poverty and the New Tuberculosis</em>. London: Verso Press.'),
    ("1988", 'Mako F, Golden J, Dialetis D, Floyd L, <strong>King NB</strong>, Kapetanakos CA. "Beam ‘Self-Trapping’ in the NRL Modified Betatron Accelerator." In Anthony Hyder, et al., Eds., <em>High-Brightness Accelerators</em>. New York: Plenum Press.'),
]

OTHER_PUBLICATIONS = [
    ("2020", '<strong>King NB</strong>. "Catastrophe Theory in Slow Motion." <em>Biosocieties</em> 15(3).'),
    ("2020", '<strong>King NB</strong>. "The politics of evidence and uncertainty in the COVID-19 pandemic." <em>The Bell: Policy for Pandemics</em>.'),
    ("2015", '<strong>King NB</strong>. "Ebola 1995/2014." <em>Limn</em> 5.'),
    ("2013", 'Harper SB, <strong>King NB</strong>. "Invited Commentary: Best Practice for What?" <em>The Milbank Quarterly</em> 91(1).'),
    ("2012", '<strong>King NB</strong>, Kaufman J. "More Author Disclosure: Solution or Absolution?" <em>Epidemiology</em> 23(6).'),
    ("2012", 'Harper SB, Kaufman JS, <strong>King NB</strong>. "Increased risk of coronary heart disease in female smokers." <em>The Lancet</em> 379(9818).'),
    ("2011", 'Kaufman JS, <strong>King NB</strong>, Harper SB. "A More Complete Picture of Higher Cardiovascular Disease Prevalence Among Blacks Compared to Whites." <em>The American Journal of Medicine</em> 124(5).'),
    ("2011", '<strong>King NB</strong>, Harper SB, et al. "We’ll Take the Red Pill: A Reply to Asada." <em>Milbank Memorial Fund Quarterly</em> 88(4).'),
    ("2010", '<strong>King NB</strong>, Kaufman JS, Harper SB. "Relative Measures Alone Tell Only Part of the Story." <em>American Journal of Public Health</em> 100.'),
    ("2009", '<strong>King NB</strong>. "Book Review – Searching Eyes: Privacy, the State, and Disease Surveillance in America." <em>Isis</em> 100.'),
    ("2009", '<strong>King NB</strong>, Harper SB. "Scan of Scenario Building in Population Health With a Focus on Social Determinants of Health." Report prepared for the Public Health Agency of Canada.'),
    ("2008", '<strong>King NB</strong>. "Book Review – Bioviolence: Preventing Biological Terror and Crime." <em>American Journal of Bioethics</em> 8(2).'),
    ("2005", '<strong>King NB</strong>. "Emerging Diseases" and "Biological Terrorism." In Sal Restivo, Ed., <em>The Oxford Encyclopedia of Science, Technology, and Society</em>. New York: Oxford University Press.'),
]

INVITED_TALKS = [
    ("May 2026", "InfluenceMapper: A Large Language Model-based Tool to Examine Sponsor Influence in Health Research", "Invited speaker, Center for Science, Policy, and Outcomes"),
    ("March 2026", "AI, Health, & Public Policy", "Invited roundtable speaker, McGill Collaborative for AI and Society"),
    ("Feb 2026", "Beyond Endless Frontiers: Rethinking the Social Contract Between Science and Society", "Invited participant, Institute on Governance"),
    ("Jan 2025", "InfluenceMapper: An Automated Tool for Tracking Sponsor Influence in Health Research", "Invited speaker, Laidley Center for Business Ethics & Equity"),
    ("Nov 2024", "Harm Reduction and the Tobacco ‘Endgame’", "Invited speaker, Université de Montréal"),
    ("Nov 2023", "Mis/disinformation in Public Health", "Invited speaker, Attention: Understanding and Shaping the Digital Media Ecosystem Conference"),
    ("Nov 2023", "Ethical Management of AI in Healthcare", "Invited moderator, Laidley Center for Business Ethics & Equity"),
    ("May 2022", "From Evidence to Policy and Back Again", "Invited speaker, Max Bell Foundation"),
    ("Feb 2022", "Defining Freedom in the Time of COVID-19", "Invited speaker, McGill University"),
    ("Jan 2022", "Science and Public Policy in a Post-Pandemic World", "Invited speaker, Université de Montréal"),
    ("Jun 2020", "Weaponizing Uncertainty During the COVID-19 Pandemic", "Invited speaker, Institute for Health and Social Policy"),
    ("Jun 2020", "Weaponizing Uncertainty During the COVID-19 Pandemic", "Invited speaker, Center for Global Health & Center for Health, Humanism and Society, Ben-Gurion University of the Negev"),
    ("Apr 2020", "Health Disparities Amid the COVID-19 Pandemic", "Invited speaker, McGill University"),
    ("Apr 2020", "Evidence and Uncertainty During the COVID-19 Pandemic", "Invited speaker, McGill University"),
    ("Oct 2019", "Pandemic Preparedness and Moral Economies of Global Health", "Invited speaker, Johns Hopkins University"),
    ("Nov 2018", "‘Just Give Cash’ or Is Money Alone the Best Option for Improving Health Justice?", "Department of Epidemiology, McGill University"),
    ("Oct 2018", "The ‘Crisis’ in Health Research", "Invited speaker, McGill University Hospital Center Medical Grand Rounds"),
    ("Sept 2018", "Opioid Narratives", "Invited speaker, McGill Research Group on Health and Law"),
    ("Sept 2018", "Harm Reduction is Neither", "Invited speaker, MANCEPT Workshops in Political Theory, the political philosophy of harm reduction"),
    ("Apr 2017", "Public Health in the ‘Post-Truth’ Era", "Invited speaker, Bowdoin College"),
    ("Jan 2017", "Quantifying Scientific Engagement: Why it Matters for Health Research, Ethics, and (Maybe) Law", "Invited speaker, McGill Research Group on Health and Law"),
    ("Jun 2016", "Health inequalities among children: what should we measure, and why?", "Invited speaker, International Network for Research on Inequalities in Child Health, Barcelona, Spain"),
    ("May 2016", "Do we care about health inequalities?", "Invited plenary, Robert Wood Johnson Health & Society Scholars Annual Meeting, New Orleans, LA"),
    ("Nov 2015", "When – if ever – is health value-added to justice claims?", "Invited speaker, Bioethics at UNC Faculty Seminar, University of North Carolina at Chapel Hill"),
    ("Nov 2015", "Reflections on the Future of Global Health", "Invited plenary, 22nd Annual Canadian Conference on Global Health"),
    ("Oct 2015", "‘Just Give Cash’ or Is Money Alone the Best Option for Improving Health Justice?", "Department of Social Medicine Forum, University of North Carolina at Chapel Hill"),
    ("Apr 2015", "It Takes Guts to Think About Health Equity", "Invited speaker, ‘Health Equity: What People Think’ workshop"),
    ("Aug 2014", "Addressing Health Disparities in Minority Populations", "Invited speaker, Association for Education in Journalism and Mass Communication Annual Meeting"),
    ("Apr 2014", "Roundtable on the Social Determinants of Health with the Official Opposition Health Critic", "Invited panelist, Lachine, QC"),
    ("Jan 2014", "Is Health Justice Impossible? Evidence, Uncertainty, and Public Policy", "Invited speaker, University of Ottawa"),
    ("Oct 2013", "Just the Facts Ma’am? On the Role of Evidence in Interdisciplinary Health Inequalities Research", "Invited speaker, University of North Carolina"),
    ("Oct 2013", "The Context-Dependence of Value Judgments About Health Inequalities", "Invited speaker, Dalhousie University"),
    ("Apr 2013", "Two Decades of Increasing Opioid-Related Mortality: Causes, Controversies, and Ethics", "Invited speaker, Lady Davis Institute for Medical Research"),
    ("Mar 2013", "At the Frontiers of Public Health Ethics: Using Mixed Methods to Study Decision-Making, Health Inequalities, and Public Health Policy", "Invited speaker, Berman Institute for Bioethics, Johns Hopkins University School of Public Health"),
    ("Dec 2012", "The Iconography of New Infectious Threats, 1936-2009", "Invited speaker, Centre for the Humanities and Medicine & Department of History, University of Hong Kong"),
    ("Jul 2012", "Bias in Health Inequalities Reporting: Systematic and Experimental Approaches", "Invited speaker, Analytical Sociology and Institutional Design Group (GSADI), Universitat Autònoma De Barcelona"),
    ("Apr 2012", "Bias in Health Inequalities Reporting: A Multidisciplinary Study", "Invited poster, Robert Wood Johnson Foundation Annual Meeting"),
    ("Oct 2011", "Justice, by the Numbers: Health Inequality Measures, and Why they Matter", "Invited speaker, Dartmouth Hitchcock Medical Center"),
    ("Jun 2011", "Public Health Ethics Frameworks: An Introduction", "Invited speaker, Canadian Public Health Association Annual Meeting"),
    ("Mar 2011", "Challenges to Integrating Ethics into Public Health Practice", "Invited speaker, National Collaborating Centre for Healthy Public Policy"),
    ("Jun 2010", "Surveillance for Decision Making in Emerging Diseases: Lessons from the 2009 H1N1 Influenza Pandemic", "Invited panelist, Harvard School of Public Health"),
    ("May 2010", "Justice, By the Numbers - or, Can Ethicists Do Policy Without Math?", "Invited speaker, Centre de Recherche En Éthique de l’Université de Montréal"),
    ("Apr 2010", "Health Justice, By the Numbers", "Invited speaker, Health Care, Technology, and Place Annual Workshop, University of Toronto"),
    ("Aug 2009", "H1N1 Pandemic Planning", "Invited speaker, The Fritz Institute, San Francisco"),
    ("May 2009", "Scenario Building and Population Health", "Invited speaker, Strategic Initiatives and Innovations Directorate, Public Health Agency of Canada workshop on Scenario-Building and Public Health"),
    ("Apr 2009", "Anthropologies of Addiction Workshop", "Invited discussant, McGill University"),
    ("Nov 2008", "Social Justice and the HIV/AIDS Epidemic", "Invited keynote, Michigan Department of Community Health STD & HIV Conference"),
    ("Jun 2008", "The Human Microbiome Project: Microbes, Medicine and Identity", "Invited panelist, Bioethics Summer Meeting"),
    ("Jun 2008", "Occupational Lung Disease: Ethical Considerations", "Invited speaker, Doctor Dorothy Wiselberg Seminar, Division of Respiratory Medicine, McGill University Health Center"),
    ("Apr 2008", "What’s Wrong with Health Inequalities?", "Invited speaker, Hixon Hour Lecture, University of Kansas Medical Center"),
    ("Mar 2008", "Hepatitis B and the Infected Healthcare Worker: Public Safety at Any Cost?", "Invited speaker, McGill University Health Center Grand Rounds, Montreal General Hospital"),
    ("Sept 2007", "What’s Wrong with Health Inequalities?", "Invited speaker, Rock Ethics Institute, Pennsylvania State University"),
    ("Feb 2007", "Expert meeting on Bioethics and Biodefense", "Invited panelist, Johns Hopkins School of Advanced International Studies"),
    ("Oct 2006", "Is Health a Useful Proxy for Social Justice?", "Invited speaker, Against Health Conference, University of Michigan"),
    ("Oct 2006", "The Soft Cage of Biosecurity? Biological Weapons and the Surveillance Convergence, 1926-2005", "Invited speaker, Department of History, Case Western Reserve University"),
    ("Apr 2006", "The Soft Cage of Biosecurity?", "Invited speaker, School of International & Public Affairs, Columbia University"),
    ("Apr 2006", "If Racial Disparities in Health are the Problem, Can Racially-Targeted Drugs be a Solution?", "Invited speaker, Race, Pharmaceuticals, and Medical Technology workshop, MIT"),
    ("Feb 2006", "Epidemics in the Making: Politics and the Production of Infectious Disease", "Invited panelist, University of Minnesota"),
    ("Apr 2005", "The Ethics of Biodefense", "Invited speaker, Stanford University"),
    ("Feb 2005", "The Ethics of Biodefense", "Invited speaker, Case Western Reserve University"),
    ("Dec 2004", "Infection and Contagion: Reflections from the Humanities", "Invited panelist, Reframing Infectious Disease conference, University of Michigan"),
    ("May 2004", "Social Science Research Council Working Group on Integrative Doctoral Programs in the Health and Social Sciences", "Invited participant"),
    ("Apr 2004", "The Iconography of New Infectious Threats", "Invited speaker, Department of Communications, University of Michigan"),
    ("Mar 2004", "The Iconography of New Infectious Threats: Disease in Public Health Films, 1936-2003", "Invited speaker, University of British Columbia"),
    ("Feb 2004", "Biodefense: History, Politics, Ethics", "Invited speaker, Rice University"),
    ("Feb 2004", "Questions of Evidence", "Invited speaker, Studying-up/Multi-sited Ethnography Workshop, University of California, Berkeley"),
    ("Oct 2003", "The Iconography of New Infectious Threats", "Invited speaker, National Library of Medicine symposium on “Visual Culture and Public Health”"),
    ("Apr 2003", "Bioterrorism and the Politics of Fear", "Invited speaker, Rensselaer Polytechnic Institute"),
    ("Nov 2002", "AAA Public Policy Forum: Bioterrorism, Epidemics, and the Future of Public Health", "Invited speaker, American Anthropological Association Annual Meeting"),
    ("Nov 2002", "Biological Threats", "Invited panelist, History of Science Society Annual Meeting"),
    ("Oct 2002", "Information is Good (and Bad) for Your Health: Utopias of Surveillance in Modern American Public Health", "Invited speaker, History and Philosophy of Science Program, Stanford University"),
    ("May 2002", "Reflections on September 11th: A Panel Discussion on its Implications for Historians of Medicine and Public Health", "Invited panelist, American Association for the History of Medicine Annual Meeting"),
    ("Apr 2002", "The Scale Politics of Emerging Diseases", "Invited speaker, Workshop on “Environment, Health and Place in Global Perspective,” University of Wisconsin, Madison"),
    ("Dec 2001", "Ebola, Emerging Diseases, and Biological Terrorism: Infectious Disease in Global Networks", "Invited speaker, Department of Anthropology, History and Social Medicine, University of California, San Francisco"),
    ("Nov 2001", "Infectious Information: Bioterrorism, Global Networks, and Urban Public Health in the Internet Age", "Invited plenary, Digital Communities: Cities in the Information Society"),
    ("May 2001", "The Practices of Ownership", "Invited commentator, Owning Up: Bodies, Selves, and the New Genetic Property, Kennedy School of Government, Harvard University"),
    ("Apr 2001", "The Empire of Biomedicine", "Invited speaker, Workshop on “Postcolonial Technoscience,” University of California at San Francisco"),
    ("May 2000", "Globalization, or a New Nativism? Race, Nation and Disease Emergence", "Invited speaker, Symposium on Race, Health, and Citizenship, Princeton University"),
]

CONFERENCE_PRESENTATIONS = [
    ("May 2020", "Similar intentions, disparate affects: Modelling ethical criteria of health equity to inform diabetes interventions using the Diabetes Population Risk Tool", "Canadian Association for Health Services and Policy Research"),
    ("May 2016", "How counseling messages are framed to parents and their influence on the reported physical activity of their children", "Pediatric Academic Societies Meeting"),
    ("Jun 2014", "Trends and demographic patterns in non-medical use of prescription opioids, 2002-2010", "Society for Epidemiologic Research Annual Meeting"),
    ("May 2014", "Health Inequalities: From measurement to policy", "Quebec Inter-University Center for Social Statistics International Conference"),
    ("Oct 2012", "Use of relative and absolute effect measures in reporting health inequalities: structured review", "ACT Now: Accuracy, Completeness and Transparency in Health Research Reporting Meeting"),
    ("Oct 2011", "The impact of framing on judgments about health inequalities", "Society for Medical Decision Making Annual Meeting"),
    ("Oct 2011", "The influence of popular media on perceptions of personal and population risk in possible disease outbreaks", "Society for Medical Decision Making Annual Meeting"),
    ("Oct 2010", "Who Cares About Health Inequalities? Findings From The World Health Survey", "Society for Medical Decision Making Annual Meeting"),
    ("Jun 2010", "Who Cares About Health Inequalities? Cross-Country Evidence from the World Health Survey", "Society for Epidemiologic Research Annual Meeting"),
    ("Jun 2009", "Visualizing Inequality", "Fourth International Conference on Interdisciplinary Social Sciences"),
    ("Mar 2009", "Mapping Equity and Efficiency in Global Health", "Association of American Geographers Annual Meeting"),
    ("Oct 2007", "All Health Inequalities are not Created Equal", "American Society for Bioethics and Humanities"),
    ("Aug 2007", "The Moral Complexity of Measurement – or, All Health Inequalities are not Created Equal", "European Conference on Philosophy of Medicine and Health Care"),
    ("Oct 2006", "Security, Justice, and the ‘Dual-Use’ Ideal in American Public Health", "Society for the Social Studies of Science Annual Meeting"),
    ("Nov 2005", "The Magic of Clinical Trials", "Invited Session, “Cultures of Chemistry: Magic, Science and Religion in the Globalization of Pharmaceuticals,” American Anthropological Association Annual Meeting"),
    ("Oct 2005", "Pharma Porn: Making the Case for Medicalization", "Society for the Social Studies of Science Annual Meeting"),
    ("Oct 2005", "The Soft Cage of Biosecurity? Biological Weapons and the Surveillance Convergence, 1926-2005", "Society for the Social Studies of Science Annual Meeting"),
    ("Oct 2004", "Pharma Porn: Corporate Advertising and the Commodification of Medicine", "American Society for Bioethics and Humanities Annual Meeting"),
    ("Nov 2002", "Information is Good (and Bad) for Your Health: Bioterrorism, Emerging Diseases, and the Globalization of Disease Surveillance Networks", "Society for the Social Studies of Science Annual Meeting"),
    ("Nov 2002", "Infectious Disease in Global Networks", "American Anthropological Association Annual Meeting"),
    ("Apr 2002", "Bioterrorism, Surveillance, and American Public Health at Millennium’s End", "West Coast History of Science Society Annual Meeting"),
    ("Nov 2001", "Dangerous Fragments: Globalization, Bioterrorism and American Anxiety in the New Millennium", "Society for the Social Studies of Science Annual Meeting"),
    ("Nov 2001", "The Contagion of Difference: Race and Disease in a Globalizing Era", "Society for the Social Studies of Science Annual Meeting"),
    ("Jan 2001", "Development and Disease Emergence", "American Historical Association Annual Meeting"),
    ("Mar 2000", "Emerging Diseases’ and 20th Century Geographies of Difference", "American Society for Environmental History Annual Meeting"),
    ("Oct 1999", "What’s New About Emerging Diseases?", "American Studies Association Annual Meeting"),
    ("Jul 1999", "Chronicle of a Disaster Foretold: Epidemic Disease as Medical Commodity", "Society for the Social History of Medicine Annual Meeting"),
    ("May 1999", "Chronicle of a Disaster Foretold: Emerging Diseases and the Political Economy of Novelty", "American Association for the History of Medicine Annual Meeting"),
    ("Nov 1997", "Emerging Diseases and the Political Economy of Novelty", "Center for Literary and Cultural Studies, Harvard University"),
]

MEDIA = [
    ("2026", "Exploring Evidence-Based Policymaking", "The Bell Podcast (22 Jan)", "https://maxbellschool.podbean.com/e/exploring-evidence-based-policymaking/"),
    ("2023", "California Expands Program That Pays People to Stop Using Drugs", "KQED Forum (5 Sept)", "https://www.kqed.org/forum/2010101894281/california-expands-program-that-pays-people-to-stop-using-drugs"),
    ("2022", "A spike in pandemic-related mental illness has overwhelmed Canada’s health care system", "The Conversationalists (24 Feb)", "https://conversationalist.org/2022/02/24/in-canada-the-pandemic-has-had-a-severe-impact-on-mental-health-but-help-is-elusive/"),
    ("2022", "Emerging health law ethics challenges with Dr. Nicholas King", "McGill Journal of Law and Health Podcast (23 Feb)", "https://anchor.fm/mcgill-journal-of-law-and-health/episodes/Emerging-health-law-ethics-challenges-with-Dr--Nicholas-King-e1eqhj0"),
    ("2022", "Defining freedom in the time of COVID", "Webcast", "https://www.youtube.com/watch?v=p98ex_FeMWA"),
    ("2021", "The pandemic exposed Montreal’s inequalities, and residents say it’s time to tackle root causes", "CBC News (3 Nov)", "https://www.cbc.ca/news/canada/montreal/covid-19-montreal-disparity-solutions-1.6232359"),
    ("2021", "Peut-on parler de « décès acceptables » de la COVID-19?", "Radio-Canada (9 Oct)", "https://ici.radio-canada.ca/nouvelle/1830245/morts-ethique-pratique-normale-sante-pandemie"),
    ("2021", "Concerns raised over travel based on type of COVID-19 vaccine received", "Global News (22 July)", "https://globalnews.ca/news/8053372/covid-vaccine-travel-inequality-coronavirus/"),
    ("2021", "COVID-19: Could Albertans choose which vaccine they get?", "Global News (5 March)", "https://globalnews.ca/news/7678348/covid-19-vaccine-choice-debate/"),
    ("2021", "Trudeau’s move to wait his turn for vaccine signals difference in political dynamics with U.S., say experts", "Hill Times (6 Jan)", "https://www.hilltimes.com/2021/01/06/trudeaus-move-to-wait-his-turn-for-vaccine-signals-difference-in-political-dynamics-with-u-s-say-experts/277464"),
    ("2020", "COVID-19 Vaccine distribution", "CTV News (9 Dec)", "https://montreal.ctvnews.ca/video?clipId=2097267"),
    ("2020", "Legault concedes Quebec’s pandemic projection data is out of date", "Montreal Gazette (16 Sept)", "https://montrealgazette.com/news/quebec/legault-concedes-quebecs-pandemic-projection-data-is-out-of-date"),
    ("2020", "Keeping accurate lists of COVID in schools not ‘mission impossible’", "Montreal Gazette (12 Sept)", "https://montrealgazette.com/news/local-news/keeping-accurate-lists-of-covid-in-schools-not-mission-impossible-parent/wcm/a6960bc5-aa8a-4142-9d02-a6d415532372/amp/"),
    ("2020", "How Canada’s first long-term coronavirus pandemic projections hold up today", "Global News (1 Aug)", "https://globalnews.ca/news/7229908/coronavirus-pandemic-projections-canada/"),
    ("2020", "Covid Conversations podcast", "(June)", "https://podcasts.apple.com/us/podcast/covid-conversations-this-overlapping-moment/id1517643497?i=1000479723792"),
    ("2020", "Racialized groups in Canada will ‘lose’ in the post-pandemic economy. Experts aren’t surprised", "Global News (21 June)", "https://globalnews.ca/news/7077024/coronavirus-economic-recovery/"),
    ("2020", "Covid-19: chi teme la riapertura e chi invece pensa all’economia", "OMNI Television (10 June)", "https://www.omnitv.ca/on/it/videos/covid-19-chi-teme-la-riapertura-e-chi-invece-pensa-alleconomia/"),
    ("2020", "Should B.C. remain an outlier when it comes to releasing locations of COVID-19 cases?", "CBC News (30 May)", "https://www.cbc.ca/news/canada/british-columbia/should-b-c-remain-an-outlier-when-it-comes-to-releasing-locations-of-covid-19-cases-1.5591600"),
    ("2020", "How we make decisions during a pandemic", "Knowable Magazine (26 May)", "https://www.knowablemagazine.org/article/mind/2020/how-we-make-decisions-during-pandemic"),
    ("2020", "Coronavirus pandemic exposing health inequities among Canadians, experts say", "Global News (25 May)", "https://globalnews.ca/news/6980483/canada-coronavirus-socioeconomic-factors/"),
    ("2020", "Florida knew a COVID-19 pandemic was likely. State leaders didn’t warn the public", "Miami Herald (20 May)", "https://www.miamiherald.com/news/health-care/article242844471.html"),
    ("2020", "COVID-19’s devastating toll on families in Montreal’s poorest neighbourhoods", "CBC News (15 May)", "https://www.cbc.ca/news/canada/montreal/montreal-low-income-inequality-covid-19-1.5570296"),
    ("2020", "Gare à l’infection volontaire", "La Presse (30 April)", "https://www.lapresse.ca/covid-19/202004/29/01-5271486-gare-a-linfection-volontaire.php"),
    ("2020", "Quebec and Ontario are hardest hit by coronavirus. Why are their reopening plans different?", "Global News (29 April)", "https://globalnews.ca/news/6881773/quebec-and-ontario-reopening-plans-coronavirus/"),
    ("2020", "The pandemic pods choosing friendship over public health", "MEL Magazine (20 April)", "https://melmagazine.com/en-us/story/the-pandemic-pods-choosing-friendship-over-public-health?"),
    ("2020", "Better late than never? What to expect from COVID-19 modeling — if Manitoba ever reveals it", "CBC News (22 April)", "https://www.cbc.ca/news/canada/manitoba/covid-19-projections-manitoba-1.5537416"),
    ("2020", "Reporting COVID-19 numbers in small communities", "CBC Radio (6 April)", "https://www.cbc.ca/listen/live-radio/1-87-quebec-am/clip/15769459-reporting-covid-19-numbers-in-small-communities"),
    ("2020", "Weaponizing Uncertainty During the COVID-19 Pandemic", "Webinar", "https://www.youtube.com/watch?v=gZxu9fg1iYU"),
    ("2020", "Health Disparities Amid the COVID-19 Pandemic", "Webinar", "https://www.mcgill.ca/maxbellschool/article/policy-challenges-during-pandemic-video/video-health-disparities-amid-covid-19-pandemic"),
    ("2020", "Evidence and Uncertainty During the COVID-19 Pandemic", "MBSPP briefing note", "https://www.mcgill.ca/maxbellschool/article/briefing-evidence-and-uncertainty-during-covid-19-pandemic"),
    ("2017", "The ethics of safe injection sites", "CTV News (2 Mar)", "https://montreal.ctvnews.ca/video?clipId=1069382&playlistId=1.3308412&binId=1.1332485&playlistPageNum=1"),
]

RESEARCH_AREAS = [
    ("Public health policy & ethics", "How value judgments, incentives, and institutions shape what counts as evidence in health policy — and who that serves."),
    ("Health inequalities & measurement", "The politics embedded in how health inequalities are measured, reported, and acted upon."),
    ("Evidence, expertise & decision-making", "How scientific evidence and expert judgment are produced, contested, and used (or ignored) in public policy."),
    ("AI, data science & public policy", "Applying and scrutinizing machine learning and large language models as tools for public health research and policy — including their own hidden assumptions."),
    ("Scientific transparency & conflicts of interest", "Automated methods for identifying industry influence and undisclosed relationships in biomedical and public health research."),
    ("History of medicine, biosecurity & risk", "How infectious disease, bioterrorism, and biosecurity have been imagined, governed, and represented since the twentieth century."),
]

SOFTWARE = [
    {
        "name": "InfluenceMapper",
        "tagline": "A large language model-based tool for identifying industry influence in health research.",
        "description": "InfluenceMapper uses large language models to automatically identify relationships to industry — funding, consulting, employment, and other undisclosed ties — in biomedical and public health research. It has been applied to carcinogenic hazard evaluations for substances including benzene, cobalt, and aspartame, and to broader questions of disclosure and conflict-of-interest detection at scale.",
        "links": [
            ("Related publication", "Environmental Health (2025)"),
            ("Related publication", "Occupational & Environmental Medicine (2025)"),
        ],
    },
]

TEACHING_COURSES = [
    ("Artificial Intelligence and Public Policy", "Max Bell School of Public Policy, McGill University", "2024–present"),
    ("Evidence, Experts, and Policy", "Max Bell School of Public Policy, McGill University", "2019–present"),
    ("Public Health Ethics and Policy", "Faculty of Medicine, McGill University", "2008–present"),
    ("Medical Ethics and Health Law", "Faculty of Medicine, McGill University", "2008–present"),
    ("Ethics and Artificial Intelligence for Public Health", "AI4PH training program", "2022–25"),
    ("The ‘Crisis’ in Health Research", "Faculty of Medicine, McGill University", "2016–23"),
    ("Bias in Medicine", "Faculty of Medicine, McGill University", "2011–16"),
    ("Health Inequalities", "Faculty of Medicine, McGill University", "2008–10"),
    ("Health and Health Care in Comparative Perspective: Costa Rica and the United States", "Department of Bioethics, Case Western Reserve University", "2008–10"),
    ("Health Inequalities and Social Justice", "Department of Bioethics, Case Western Reserve University", "2006–08"),
    ("Everything for Sale", "Case Western Reserve University", "2006"),
    ("On Pain", "Department of the History of Science, Harvard University", "1997–98"),
]

TEACHING_AWARDS = [
    ("2017/18, 2019/20, 2025/26", "Thank a Prof Teaching Award, McGill University"),
    ("2024", "Faculty Honour List for Educational Excellence, McGill University Faculty of Medicine"),
    ("2022", "Epidemiology, Biostatistics, and Occupational Health Student Society, for Excellence in Teaching Public Health, McGill University"),
    ("2018", "Epidemiology, Biostatistics, and Occupational Health Student Society, for Excellence in Teaching Public Health, McGill University"),
    ("2011", "Epidemiology, Biostatistics, and Occupational Health Student Society, Senior Teaching Award, Best Course, McGill University"),
    ("2010", "Epidemiology, Biostatistics, and Occupational Health Student Society, Senior Teaching Award, Best Course, McGill University"),
    ("2007", "Finalist, Wittke Undergraduate Teaching Award, Case Western Reserve University"),
    ("2000", "Certificate of Distinction in Teaching, Harvard University"),
    ("1999", "Certificate of Distinction in Teaching, Harvard University"),
    ("1998", "Certificate of Distinction in Teaching, Harvard University"),
]

APPOINTMENTS_CURRENT = [
    ("Associate Professor", "Department of Equity, Ethics, & Policy, Faculty of Medicine", "2023–present"),
    ("Associate Director", "Trottier Institute for Science & Public Policy", "2026–present"),
    ("Core Faculty Member", "Max Bell School of Public Policy", "2019–present"),
    ("Associate Member", "Department of Epidemiology, Biostatistics and Occupational Health", "2009–present"),
    ("Associate Member", "Department of Medicine", "2018–present"),
    ("Associate Member", "Division of Experimental Medicine", "2018–present"),
    ("Associate Member", "Research Group on Health and Law", "2015–present"),
]

APPOINTMENTS_PREVIOUS = [
    ("Assistant & Associate Professor", "Biomedical Ethics Unit / Department of Social Studies of Medicine, McGill University", "2008–23"),
    ("Director", "Policy and Data Science Program, McGill University", "2017–20"),
    ("Director", "Montreal Health Equity Research Consortium, McGill University", "2011–17"),
    ("Director", "Measurement, Ethics, and Decision-Making Collaborative, McGill University", "2010–16"),
    ("Assistant Professor", "Department of Bioethics / Department of History, Case Western Reserve University", "2005–08"),
    ("Postdoctoral Fellow", "Robert Wood Johnson Foundation Health and Society Scholars, Dept. of Epidemiology, University of Michigan", "2003–05"),
    ("J. Elliot Royer Postdoctoral Fellow", "Dept. of Anthropology, History, and Social Medicine, UCSF", "2001–03"),
]

SELECTED_GRANTS = [
    ("2020–24", "Principal Investigator ($250,000)", "New Frontiers in Research Fund. Automating Scientific Transparency: Using Machine Learning to Build a Comprehensive Database of Disclosure Information."),
    ("2011–16", "Principal Investigator ($1.74 million)", "Canadian Institutes of Health Research. Ethics, Social Determinants of Health, and Health Equity: Integrating Theory and Practice."),
    ("2020–22", "Co-Investigator ($525,000)", "Canadian Institutes of Health Research. Artificial Intelligence for Public Health (AI4PH): A Focus on Equity and Prevention."),
    ("2020–22", "Co-Investigator (£604,318.87)", "Canada-UK Artificial Intelligence (AI) Initiative. EPI-AI: Automated Understanding and Alerting of Disease Outbreaks from Global News Media."),
    ("2020–22", "Co-Investigator ($500,000)", "Canadian Institutes of Health Research. Using Online News Media to Assess Community and Public Health Responses to COVID-19."),
    ("2010–13", "Principal Investigator ($190,434)", "Canadian Institutes of Health Research. Measurement, Ethics, and Health Policy: Investigating the Role of Value Judgments in the Measurement and Evaluation of Health Inequalities."),
]

# Links to original sources, supplied by Nicholas King from his existing site
# (nicholasbking.net). Keyed by the exact publication HTML string above, or by
# (date, title) for talks. Only entries with a confirmed source link are included.

PUBLICATION_LINKS = {
    'DeBono N, Amar V*, Hardy H*, Schubauer-Berigan M, Ruths D, <strong>King NB</strong>. "The use of a large language model to identify industry-funded research in carcinogenic hazard evaluations." <em>Occupational &amp; Environmental Medicine</em> 82.': "https://oem.bmj.com/content/82/Suppl_2/A87.3.abstract",
    'Trudeau C*, <strong>King NB</strong>, Guastavino C. "Investigating sonic injustice: a review of published research." <em>Social Science &amp; Medicine</em> 326.': "https://www.sciencedirect.com/science/article/pii/S0277953623002769?",
    'Dimitris M*, Gittings M*, <strong>King NB</strong>. "How Global is Global Health Research? A Large-Scale Analysis of Trends in Authorship." <em>BMJ Global Health</em> 6(1).': "https://gh.bmj.com/content/6/1/e003758",
    'Harper SB, Riddell C*, <strong>King NB</strong>. "Declining Life Expectancy in the United States: Missing the Trees for the Forest." <em>Annual Review of Public Health</em> 42(1).': "https://www.annualreviews.org/doi/pdf/10.1146/annurev-publhealth-082619-104231",
    '<strong>King NB</strong>. "Harm Reduction: A Misnomer." <em>Health Care Analysis</em> 28.': "https://link.springer.com/article/10.1007/s10728-020-00413-x?",
    'Cooper JE*, Benmarhnia T*, Koski A, <strong>King NB</strong>. "Cash transfer programs have differential effects on health: A review of the literature from low and middle-income countries." <em>Social Science &amp; Medicine</em> 247.': "https://www.sciencedirect.com/science/article/abs/pii/S0277953620300253",
    '<strong>King NB</strong>, Koski A. "Defining global health as public health somewhere else." <em>BMJ Global Health</em> 5:e002172.': "https://gh.bmj.com/content/5/1/e002172.abstract",
    'Carabali M*, Austin N*, <strong>King NB</strong>, Kaufman J. "The zika epidemic and abortion in Latin America: a scoping review." <em>Global Health Research and Policy</em> 3(15).': "https://ghrp.biomedcentral.com/articles/10.1186/s41256-018-0069-8",
    '<strong>King NB</strong>, Harper SB, Young M, Berry SC, Voigt K*. "The Impact of Social and Psychological Consequences of Disease on Judgments of Disease Severity: An Experimental Study." <em>PLOS ONE</em> 13(4).': "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0195338",
    'Huang J*, <strong>King NB</strong>. "Epigenetics Changes Nothing: What a New Scientific Field Does and Does Not Mean for Social Justice." <em>Public Health Ethics</em> 11(1).': "https://academic.oup.com/phe/article-abstract/doi/10.1093/phe/phx013/4082556/Epigenetics-Changes-Nothing-What-a-New-Scientific",
    'Voigt K*, <strong>King NB</strong>. "Out of alignment? Limitations of the Global Burden of Disease in assessing the allocation of global health aid." <em>Public Health Ethics</em> 10(3).': "https://academic.oup.com/phe/article/4082024/Out-of-Alignment-Limitations-of-the-Global-Burden",
    'Benmarhnia T*, Alexander S, Price K, Smargiassi S, <strong>King NB</strong>, Kaufman J. "The heterogeneity of vulnerability in public health: a heat wave action plan as a case study." <em>Critical Public Health</em> 28.': "https://www.tandfonline.com/doi/abs/10.1080/09581596.2017.1322176",
    '<strong>King NB</strong>, Harper SB, Strumpf E. "Has the Increase in Disability Insurance Participation Contributed to Increased Opioid-Related Mortality?" <em>Annals of Internal Medicine</em> 165(10): 729–730.': "https://www.acpjournals.org/doi/10.7326/M16-0918",
    'Campbell J*, <strong>King NB</strong>. "‘Unsettling Circularity’: Clinical Trial Enrichment and the Evidentiary Politics of Chronic Pain." <em>Biosocieties</em> 12(2).': "https://link.springer.com/article/10.1057/biosoc.2016.7",
    'Benmarhnia T*, Auger N, Kaiser D, Bailey Z*, <strong>King NB</strong>, Kaufman J. "A difference-in-differences approach to assess the effect of a heat action plan on heat-related mortality and equity in Montreal, Quebec." <em>Environmental Health Perspectives</em> 24(11). <span class="note">Honorable Mention, Best Environmental Epidemiology Papers of 2016, International Society for Environmental Epidemiology.</span>': "https://ehp.niehs.nih.gov/ehp203/",
    # Book chapters
    '<strong>King NB</strong>. "Science and Public Policy in a Post-Pandemic World." In Jean-Louis Denis, Catherine Régis &amp; Daniel Weinstock, Eds., <em>Pandemic Societies</em>. Montreal: McGill-Queen’s University Press.': "files/King_2021_Science_and_Public_Policy_in_a_PostPandemic_World.pdf",
    '<strong>King NB</strong>. "Technological Fixes and Antimicrobial Resistance." In Zeb Jamrozik &amp; Michael Selgelid, Eds., <em>Ethics and Antimicrobial Resistance: Collective Responsibility for Global Public Health</em>.': "https://link.springer.com/chapter/10.1007/978-3-030-27874-8_19",
    '<strong>King NB</strong>. "Justice, Evidence, and Interdisciplinary Health Inequalities Research." In Mara Buchbinder, Ed., <em>Understanding Health Inequalities and Justice: Bridging Perspectives for New Conversations</em>. University of North Carolina Press.': "https://muse.jhu.edu/pub/12/edited_volume/chapter/1874279/pdf",
    # Other publications
    '<strong>King NB</strong>. "Catastrophe Theory in Slow Motion." <em>Biosocieties</em> 15(3).': "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7453081/#Sec12title",
    '<strong>King NB</strong>. "The politics of evidence and uncertainty in the COVID-19 pandemic." <em>The Bell: Policy for Pandemics</em>.': "https://maxpolicy.substack.com/p/issue-11-the-politics-of-evidence",
    '<strong>King NB</strong>. "Ebola 1995/2014." <em>Limn</em> 5.': "https://limn.it/ebola-19952014/",
}

# Webinar / video links for talks, keyed by (date, title) as they appear in INVITED_TALKS.
TALK_LINKS = {
    ("Feb 2022", "Defining Freedom in the Time of COVID-19"): "https://www.youtube.com/watch?v=p98ex_FeMWA",
    ("Jun 2020", "Weaponizing Uncertainty During the COVID-19 Pandemic"): "https://www.youtube.com/watch?v=gZxu9fg1iYU",
    ("Apr 2020", "Health Disparities Amid the COVID-19 Pandemic"): "https://www.mcgill.ca/maxbellschool/article/policy-challenges-during-pandemic-video/video-health-disparities-amid-covid-19-pandemic",
    ("Apr 2020", "Evidence and Uncertainty During the COVID-19 Pandemic"): "https://www.mcgill.ca/maxbellschool/article/briefing-evidence-and-uncertainty-during-covid-19-pandemic",
}
